### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by arvl130** [arvl130/lfidentalclinic-laravel-api#1]
Here is a list of routes we have to port:

## Messages
- [x] `GET` /messages
- [x] `PUT` /messages
- [x] `PATCH` /messages/[uid]
- [x] `DELETE` /messages/[uid]/delete

## Reminders
- [x] `GET` /reminders
- [x] `POST` /reminders

## Appointments
- [x] `GET` /appointments/[year]/[month]
- [x] `GET` /appointments/requesting-procedure-access

## Timeslots
- [x] `PUT` /timeslots/appointments
- [x] `DELETE` /timeslots/appointments/[slotSeconds]
- [x] `PUT` /timeslots/closed
- [x] `DELETE` /timeslots/closed/[slotSeconds]
- [x] `GET` /timeslots/unavailable/[year]/[month]

## Auth
- [x] `POST` /auth/register/admin
- [x] `POST` /auth/register
- [x] `POST` /auth/login
- [x] `POST` /auth/logout
- [x] `GET` /auth/user
- [x] `POST` /auth/user/name

## Users
- [x] `GET` /users/archived/search/by-name/[nameFilter]
- [x] `GET` /users/archived
- [x] `GET` /users/search/by-name/[nameFilter]
- [x] `GET` /users

## User profile
- [x] `GET` /users/[patientUid]
- [x] `POST` /users/[patientUid]/archived
- [x] `DELETE` /users/[patientUid]/archived

## User Appointments
- [x] `GET` /users/[patientUid]/appointments
- [x] `PUT` /users/[patientUid]/appointments
- [x] `POST` /users/[patientUid]/appointments/[slotSeconds]/payment
- [x] `DELETE` /users/[patientUid]/appointments/[slotSeconds]/cancel
- [x] `DELETE` /users/[patientUid]/appointments/[slotSeconds]/delete
- [x] `PUT` /users/[patientUid]/appointments/[slotSeconds]/attended
- [x] `PATCH` /users/[patientUid]/appointments/[slotSeconds]/attended
- [x] `DELETE` /users/[patientUid]/appointments/[slotSeconds]/attended
- [x] `GET` /users/[patientUid]/appointments/[slotSeconds]/procedure
- [x] `PATCH` /users/[patientUid]/appointments/[slotSeconds]/procedure
- [x] `PUT` /users/[patientUid]/appointments/[slotSeconds]/procedure/access
- [x] `DELETE` /users/[patientUid]/appointments/[slotSeconds]/procedure/access
- [x] `PUT` /users/[patientUid]/appointments/[slotSeconds]/procedure/request-access
- [x] `DELETE` /users/[patientUid]/appointments/[slotSeconds]/procedure/request-access

## User Signatures
- [x] `GET` /users/[patientUid]/signatures/guardian
- [x] `PATCH` /users/[patientUid]/signatures/guardian
- [x] `GET` /users/[patientUid]/signatures/patient
- [x] `PATCH` /users/[patientUid]/signatures/patient

## User Dental charts
- [x] `GET` /users/[patientUid]/charts/medical-chart/filled-in
- [x] `POST` /users/[patientUid]/charts/medical-chart/filled-in
- [x] `GET` /users/[patientUid]/charts/medical-chart
- [x] `PATCH` /users/[patientUid]/charts/medical-chart
- [x] `GET` /users/[patientUid]/charts/dental-chart
- [x] `PATCH` /users/[patientUid]/charts/dental-chart
- [x] `GET` /users/[patientUid]/charts/deciduous-chart
- [x] `PATCH` /users/[patientUid]/charts/deciduous-chart

## User Assessment forms
- [x] `GET` /users/[patientUid]/forms/assessment
- [x] `PATCH` /users/[patientUid]/forms/assessment
- [x] `GET` /users/[patientUid]/forms/consent
- [x] `PATCH` /users/[patientUid]/forms/consent
